all:
  vars:
    github_user_pubkeys:
      - protolambda
      - djrtwo
      - ralexstokes
    ansible_user: "ubuntu"
    eth1endpoint: http://127.0.0.1:8545
    eth1_rpc_port: 8545
    eth1_ws_rpc_port: 8546
    nimbus_rpc_port: 4009
    beacon_api_port: 4000
    beacon_grpc_port: 4001
    beacon_metrics_port: 8000
    beacon_p2p_port: 9000
    letsencrypt_email: proto@protolambda.com
    forkmon_domain: fork.nocturne.rayonism.io
    explorer_domain: nocturne.rayonism.io
    graffiti: "proto {{eth2_client_name}} {{eth1_client_name}}"
    local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
    local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
    local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
    local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
    local_networkdata_host_dir: "{{inventory_dir}}/../networkdata"
    local_networkdata_host_archive: "{{inventory_dir}}/../networkdata.tar.gz"
    # private dirs
    local_validator_host_dir: "{{inventory_dir}}/../keystore_prep/validators/{{valname}}"
    local_validator_host_archive: "{{inventory_dir}}/../keystore_prep/validators/{{valname}}.tar.gz"
    bootnode_enrs:
        # proto teku 101
      - "enr:-foobar" # TODO
  hosts:
    noct_101:
      valname: val101
      ansible_host: 18.221.225.249
      public_ip_address: 18.221.225.249
    noct_102:
      valname: val102
      ansible_host: 18.191.99.99
      public_ip_address: 18.191.99.99
    noct_103:
      valname: val103
      ansible_host: 13.59.26.83
      public_ip_address: 13.59.26.83
    noct_104:
      valname: val104
      ansible_host: 18.222.199.228
      public_ip_address: 18.222.199.228
    noct_105:
      valname: val105
      ansible_host: 18.216.123.250
      public_ip_address: 18.216.123.250
    noct_106:
      valname: val106
      ansible_host: 3.137.189.12
      public_ip_address: 3.137.189.12
    noct_107:
      valname: val107
      ansible_host: 3.133.90.91
      public_ip_address: 3.133.90.91
    noct_108:
      valname: val108
      ansible_host: 18.220.33.80
      public_ip_address: 18.220.33.80
    noct_109:
      valname: val109
      ansible_host: 18.224.252.227
      public_ip_address: 18.224.252.227
    noct_110:
      valname: val110
      ansible_host: 3.141.197.255
      public_ip_address: 3.141.197.255
    noct_111:
      valname: val111
      ansible_host: 18.117.9.14
      public_ip_address: 18.117.9.14
    noct_112:
      valname: val112
      ansible_host: 18.219.69.72
      public_ip_address: 18.219.69.72

    forkmon0:  # noct_601
      ansible_host: 18.219.192.38
      public_ip_address: 18.219.192.38
    explorer0:  # noct_701
      ansible_host: 18.188.159.150
      public_ip_address: 18.188.159.150
    metrics0:  # noct_801
      ansible_host: 3.143.205.242
      public_ip_address: 3.143.205.242
    bootnode0:  # noct_901
      ansible_host: 3.128.171.66
      public_ip_address: 3.128.171.66
      bootnode_p2p_priv_key: "{{lookup('env', 'NOCTURNE_BOOTNODE0_PRIV')}}"

  children:
    bootnode:
      hosts:
        bootnode0:
    forkmon:
      hosts:
        forkmon0:
    metrics:
      hosts:
        metrics0:
    beacon:
      hosts:
        explorer0:
        noct_101:
        noct_102:
        noct_103:
        noct_104:
        noct_105:
        noct_106:
        noct_107:
        noct_108:
        noct_109:
        noct_110:
        noct_111:
        noct_112:
    validator:
      hosts:
        noct_101:
        noct_102:
        noct_103:
        noct_104:
        noct_105:
        noct_106:
        noct_107:
        noct_108:
        noct_109:
        noct_110:
        noct_111:
        noct_112:
    eth1:
      hosts:
        explorer0:
        noct_101:
        noct_102:
        noct_103:
        noct_104:
        noct_105:
        noct_106:
        noct_107:
        noct_108:
        noct_109:
        noct_110:
        noct_111:
        noct_112:
    teku:
      hosts:
        noct_101:
        noct_102:
        noct_103:
    prysm:
      hosts:
        explorer0:
        noct_104:
        noct_105:
        noct_106:
    lighthouse:
      hosts:
        noct_107:
        noct_108:
        noct_109:
    nimbus:
      hosts:
        noct_110:
        noct_111:
        noct_112:
    geth:
      hosts:
        explorer0:
        noct_101:
        noct_104:
        noct_107:
        noct_110:
    besu:
      hosts:
        noct_102:
        noct_105:
        noct_108:
        noct_111:
    nethermind:
      hosts:
        noct_103:
        noct_106:
        noct_109:
        noct_112:

