# disabled
weak_subjectivity_provider_endpoint: ""
# disabled
etherscan_api_key: ""
http_timeout_milliseconds: 2000
endpoints:
  - addr: 18.116.163.253:4000  # noct_101
    eth1: Geth
  - addr: 18.191.134.142:4000  # noct_102
    eth1: Besu
  - addr: 18.222.141.47:4000  # noct_103
    eth1: Nethermind
  - addr: 3.141.152.61:4000  # noct_104
    eth1: Geth
  - addr: 18.220.203.87:4000  # noct_105
    eth1: Besu
  - addr: 18.191.229.251:4000  # noct_106
    eth1: Nethermind
  - addr: 3.138.193.82:4000  # noct_107
    eth1: Geth
  - addr: 3.16.214.210:4000  # noct_108
    eth1: Besu
  - addr: 3.131.128.170:4000  # noct_109
    eth1: Nethermind
  - addr: 3.129.15.0:4000  # noct_110
    eth1: Geth
  - addr: 3.19.234.64:4000  # noct_111
    eth1: Besu
  - addr: 3.17.26.179:4000  # noct_112
    eth1: Nethermind

outputDir: /public
eth2:
  seconds_per_slot: 12
  genesis_time: 1620820800
  slots_per_epoch: 32
  network: steklo
