all:
  vars:
    github_user_pubkeys:
      - protolambda
      - djrtwo
      - ralexstokes
    ansible_user: "ubuntu"
    eth1endpoint: http://127.0.0.1:8500
    eth1_rpc_port: 8500
    beacon_api_port: 4000
    beacon_metrics_port: 8000
    beacon_p2p_port: 9000
    beacon_endpoint: http://127.0.0.1:4000
  hosts:
    bootnode0:
      vars:  # TODO
        ansible_host: 1.2.3.4
        public_ip_address: 1.2.3.4
        bootnode_p2p_priv_key: "{{lookup('env', 'STEKLO_BOOTNODE0_PRIV')}}"
    teku0:
      vars:
        ansible_host: 1.2.3.4
        public_ip_address: 1.2.3.4
    teku1:
      vars:
        ansible_host: 1.2.3.4
        public_ip_address: 1.2.3.4
  children:
    bootnode:
      hosts:
        bootnode0:
    teku:
      hosts:
        teku0:
        teku1:
