all:
  vars:
    github_user_pubkeys:
      - protolambda
      - djrtwo
      - ralexstokes
    ansible_user: "ubuntu"
    eth1endpoint: http://127.0.0.1:8545
    eth1endpoint_ws: ws://127.0.0.1:8546/ws
    eth1_rpc_port: 8545
    eth1_ws_rpc_port: 8546
    nimbus_rpc_port: 4009
    beacon_api_port: 4000
    beacon_grpc_port: 4001
    beacon_metrics_port: 8000
    beacon_p2p_port: 9000
    letsencrypt_email: proto@protolambda.com
    graffiti: "proto {{eth2_client_name}} {{eth1_client_name}}"
    local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
    local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
    local_networkdata_host_dir: "{{inventory_dir}}/../networkdata"
    local_networkdata_host_archive: "{{inventory_dir}}/../networkdata.tar.gz"
    # private dirs
    local_validator_host_dir: "{{inventory_dir}}/../keystore_prep/validators/{{valname}}"
    local_validator_host_archive: "{{inventory_dir}}/../keystore_prep/validators/{{valname}}.tar.gz"
    bootnode_enrs:
        # proto bootnode0 (discv5, no full beacon node)
      - "enr:-Ku4QFrzIH_DETC3gh3Dhl_rMzNOdlUH427ef3lbtArKVvbaX_YVs6_zEB0Z5Q72a6ZKlgvXJjS-yt20UXhftrFS2EoCh2F0dG5ldHOIAAAAAAAAAACEZXRoMpB5-A5dAAAHAf__________gmlkgnY0gmlwhANDKQyJc2VjcDI1NmsxoQIOfbH-pbhkBiSvD0wJxyjm8vA4DROacA7uT4Nfdc5QDYN1ZHCCIyg"
        # Sigma Prime (Lighthouse): ap-southeast
      - "enr:-LK4QJO02L_YsaXjI0OUw_mIcfInBLiy9pqE2j6S8gyvVG31f2pemsBQWKSzh1o6FYKqkDYOOKCMRymcwvGqxHRXm0oBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpB5-A5dAAAHAf__________gmlkgnY0gmlwhA3UIxiJc2VjcDI1NmsxoQK-Ul9MNUZLNn5uITHeEwg8z4h26vshUJmux6yQm0d9ooN0Y3CCIyiDdWRwgiMo"
        # Sigma Prime (Lighthouse): eu-central
      - "enr:-LK4QIVjWVem2LJoSZkqFLx0QM0xVJLD18jHZSNwUsMcqO0yaL_2bFznCLknH8hz9K2hPmPUUnfFsWPJfUwpgzOGNooBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpB5-A5dAAAHAf__________gmlkgnY0gmlwhANComqJc2VjcDI1NmsxoQOEccHNC733KCWsZFgRl7PctIYwbiHFrV-OIOtwvSFx14N0Y3CCIyiDdWRwgiMo"
        # Sigma Prime (Lighthouse): ap-south
      - "enr:-LK4QF0gc-Zj5y4k6typswN5ZYaYp1OIuNxgb0lhl7idG78OIsrmCOR5STJQT9RMp0tysjTElmp0hwaKmxizo_KyKOABh2F0dG5ldHOIAAAAAAAAAACEZXRoMpB5-A5dAAAHAf__________gmlkgnY0gmlwhAMHJfSJc2VjcDI1NmsxoQPwt51JI8k5b2cc1tcotu3BrjY2MOSOycIyBnpf5_LHX4N0Y3CCIyiDdWRwgiMo"
        # Sigma Prime (Lighthouse): us-west
      - "enr:-LK4QGDdr6pFuRO95rX4HoMWbrhTqr_o26e2QgQVZBgoGQDAc207JcOqaf2lXxufVqCgSZ9Sevm0sywquBFTp94o3GkBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpB5-A5dAAAHAf__________gmlkgnY0gmlwhCNQDTuJc2VjcDI1NmsxoQI4ptVL1_Buv7If42yf1hfPJdvtsa36k4otY0OoYGBTYYN0Y3CCIyiDdWRwgiMo"

  hosts:
    bootnode0:
      ansible_host: 3.67.41.12
      public_ip_address: 3.67.41.12
      bootnode_p2p_priv_key: "{{lookup('env', 'STEKLO_BOOTNODE0_PRIV')}}"
    forkmon0:
      ansible_host: 3.18.108.10
      public_ip_address: 3.18.108.10
    steklo_101:
      valname: val101
      ansible_host: 13.58.214.185
      public_ip_address: 13.58.214.185
    steklo_102:
      valname: val102
      ansible_host: 18.222.204.97
      public_ip_address: 18.222.204.97
    steklo_103:
      valname: val103
      ansible_host: 18.188.77.212
      public_ip_address: 18.188.77.212
    steklo_104:
      valname: val104
      ansible_host: 18.116.48.218
      public_ip_address: 18.116.48.218
    steklo_105:
      valname: val105
      ansible_host: 3.143.222.213
      public_ip_address: 3.143.222.213
    steklo_106:
      valname: val106
      ansible_host: 3.142.153.99
      public_ip_address: 3.142.153.99
    steklo_107:
      valname: val107
      ansible_host: 3.135.222.111
      public_ip_address: 3.135.222.111
    steklo_108:
      valname: val108
      ansible_host: 13.58.244.10
      public_ip_address: 13.58.244.10
    steklo_109:
      valname: val109
      ansible_host: 3.143.110.171
      public_ip_address: 3.143.110.171
    steklo_110:
      valname: val110
      ansible_host: 13.59.125.194
      public_ip_address: 13.59.125.194
    steklo_111:
      valname: val111
      ansible_host: 3.142.146.214
      public_ip_address: 3.142.146.214
    steklo_112:
      valname: val112
      ansible_host: 3.17.158.14
      public_ip_address: 3.17.158.14
    steklo_901:
      ansible_host: 3.142.40.70
      public_ip_address: 3.142.40.70
  children:
    bootnode:
      hosts:
        bootnode0:
    forkmon:
      hosts:
        forkmon0:
    metrics:
      hosts:
        steklo_901:
    beacon:
      hosts:
        steklo_101:
        steklo_102:
        steklo_103:
        steklo_104:
        steklo_105:
        steklo_106:
        steklo_107:
        steklo_108:
        steklo_109:
        steklo_110:
        steklo_111:
        steklo_112:
    validator:
      hosts:
        steklo_101:
        steklo_102:
        steklo_103:
        steklo_104:
        steklo_105:
        steklo_106:
        steklo_107:
        steklo_108:
        steklo_109:
        steklo_110:
        steklo_111:
        steklo_112:
    eth1:
      hosts:
        steklo_101:
        steklo_102:
        steklo_103:
        steklo_104:
        steklo_105:
        steklo_106:
        steklo_107:
        steklo_108:
        steklo_109:
        steklo_110:
        steklo_111:
        steklo_112:
    teku:
      hosts:
        steklo_101:
        steklo_102:
        steklo_103:
    prysm:
      hosts:
        steklo_104:
        steklo_105:
        steklo_106:
    lighthouse:
      hosts:
        steklo_107:
        steklo_108:
        steklo_109:
    nimbus:
      hosts:
        steklo_110:
        steklo_111:
        steklo_112:
    geth:
      hosts:
        steklo_101:
        steklo_104:
        steklo_107:
        steklo_110:
    besu:
      hosts:
        steklo_102:
        steklo_105:
        steklo_108:
        steklo_111:
    nethermind:
      hosts:
        steklo_103:
        steklo_106:
        steklo_109:
        steklo_112:

