common_log_options:
  max-file: "10"
  max-size: 30m
  mode: non-blocking
  max-buffer-size: 4m

common_log_driver: json-file

home_dir: "/home/{{ ansible_user }}"

beacon_container_name: beacon
validator_container_name: validator
eth1_container_name: eth1

# TODO: override bootnode_enr
bootnode_enr: ""


validator_user_id: "1000:1000"
beacon_user_id: "1000:1000"


node_exporter_web_listen_address: "0.0.0.0:8100"
beacon_metrics_port: 8000
beacon_p2p_port: 9000
