eth1_client_name: besu
eth1_image_name: suburbandad/besu:rayonism

eth1_memory: 5000M
eth1_kernel_memory: 5500M

# websocket with /ws suffix
eth1endpoint_ws: ws://127.0.0.1:8546/ws

eth1_volumes:
  - "{{eth1_node_dir}}:/besudata"
  - "{{testnet_dir}}/eth1_config.json:/networkdata/eth1_config.json"

eth1_start_args: >
  --data-path="/besudata"
  --genesis-file="/networkdata/eth1_config.json"
  --rpc-http-enabled --rpc-http-api=ETH,NET,CONSENSUS
  --rpc-http-host=0.0.0.0
  --rpc-http-port={{eth1_rpc_port}}
  --rpc-http-cors-origins="*"
  --rpc-ws-enabled --rpc-ws-api=ETH,NET,CONSENSUS
  --rpc-ws-host=0.0.0.0
  --rpc-ws-port={{eth1_ws_rpc_port}}
  --Xmerge-support=true
  --discovery-enabled=false
  --miner-coinbase="0x1000000000000000000000000000000000000000"

eth1_user_id: "1000:1000"
