forkmon_container_name: forkmon
forkmon_memory: 3000m
# Not the image of alex, this contains a bugfix for missing "data" field in api response
forkmon_image_name: "protolambda/eth2-fork-mon:latest"

forkmon_host_dir: "{{home_dir}}/forkmon_data"

forkmon_volumes:
  - "{{forkmon_host_dir}}:/data"

forkmon_start_args: "-config-file=/data/config.yaml"
