forkmon_container_name: forkmon
forkmon_memory: 3000m
forkmon_image_name: ralexstokes/eth2-fork-mon

forkmon_virtual_port: 8080

forkmon_host_dir: "{{home_dir}}/forkmon_data"

forkmon_volumes:
  - "{{forkmon_host_dir}}:/data"

forkmon_start_args: "-config-file=/data/config.yaml"
