eth1_client_name: catalyst
eth1_image_name: ethereum/client-go:latest

eth1_memory: 5000M
eth1_kernel_memory: 5500M

eth1_volumes:
  - "{{eth1_node_dir}}:/gethdata"
  - "{{testnet_dir}}/eth1_config.json:/networkdata/eth1_config.json"

geth_init_args: >
  --catalyst
  --datadir "/gethdata/chaindata"
  init "/networkdata/eth1_config.json"

eth1_start_args: >
  --catalyst
  --http --http.api net,eth,consensus
  --http.port {{eth1_rpc_port}}
  --http.addr 0.0.0.0
  --nodiscover
  --miner.etherbase 0x1000000000000000000000000000000000000000
  --datadir "/gethdata/chaindata"

eth1_user_id: "1000:1000"
