eth1_client_name: nethermind
eth1_image_name: nethermind/nethermind:latest

eth1_rpc_port: 8545

eth1_volumes:
  - "{{node_dir}}:/netherminddata"
  - "{{testnet_dir}}/eth1_nethermind_config.json:/networkdata/eth1_nethermind_config.json"

eth1_start_args: >
  -c catalyst
  --datadir "/netherminddata"
  --Init.ChainSpecPath "/networkdata/eth1_nethermind_config.json"
  --JsonRpc.Port {{eth1_rpc_port}}
  --JsonRpc.Host 0.0.0.0
  --Merge.BlockAuthorAccount 0x1000000000000000000000000000000000000000

# run as root, the nethermind image doesn't handle running regular user well
eth1_user_id: "0:0"
