eth1_client_name: nethermind
eth1_image_name: nethermind/nethermind:latest

eth1_memory: 5000M
eth1_kernel_memory: 5500M

# websocket with upgrade
eth1endpoint_ws: http://127.0.0.1:8546

eth1_volumes:
  - "{{eth1_node_dir}}:/netherminddata"
  - "{{testnet_dir}}/eth1_nethermind_config.json:/networkdata/eth1_nethermind_config.json"

eth1_start_args: >
  -c catalyst
  --datadir "/netherminddata"
  --Init.ChainSpecPath "/networkdata/eth1_nethermind_config.json"
  --Init.WebSocketsEnabled true
  --JsonRpc.Port {{eth1_rpc_port}}
  --JsonRpc.WebSocketsPort {{eth1_ws_rpc_port}}
  --JsonRpc.Host 0.0.0.0
  --Merge.BlockAuthorAccount 0x1000000000000000000000000000000000000000

# run as root, the nethermind image doesn't handle running regular user well
eth1_user_id: "0:0"
