eth2_client_name: nimbus
beacon_image_name: protolambda/nimbus:rayonism
validator_image_name: protolambda/nimbus:rayonism

beacon_memory: 5000M
beacon_kernel_memory: 5500M

beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"

beacon_start_args: >
  beacon_node
  --network=steklo
  --max-peers="60"
  --data-dir="/beacondata"
  --web3-url="{{eth1endpoint_ws}}"
  {% for bootnode_enr in bootnode_enrs %}
  --bootstrap-node="{{ bootnode_enr }}"
  {% endfor %}
  --udp-port={{beacon_p2p_port}}
  --tcp-port={{beacon_p2p_port}}
  --listen-address=0.0.0.0
  --graffiti="{{graffiti}}"
  --nat="extip:{{public_ip_address}}"
  --enr-auto-update=false
  --rpc --rpc-port={{nimbus_rpc_port}} --rpc-address=0.0.0.0
  --rest --rest-port={{beacon_api_port}} --rpc-address=0.0.0.0
  --metrics --metrics-port={{beacon_metrics_port}} --metrics-address=0.0.0.0
  --log-level="{{ beacon_log_level | upper }}"
  --log-file="/dev/null"


validator_memory: 2000M
validator_kernel_memory: 2500M


validator_volumes:
  - "{{validator_node_dir}}:/validatordata"
  # Note: nimbus validators fetch the spec config from the beacon node

validator_start_args: >
  validator_client
  --log-level="debug"
  --log-file="/dev/null"
  --data-dir="/validatordata"
  --non-interactive=true
  --graffiti="{{graffiti}}"
  --rpc-port={{nimbus_rpc_port}}
  --rpc-address=127.0.0.1
  --validators-dir="/validatordata/keys"
  --secrets-dir="/validatordata/secrets"

# TODO: might have to mod this to 0600 later. Archive-upload with 0600 fails, need to mod after unarchiving
keystores_file_mode: "0700"

beacon_user_id: "1000:1000"
validator_user_id: "1000:1000"
