- name: Init geth node
  hosts: geth
  gather_facts: true
  serial: 20
  tasks:
    - name: Run geth init
      docker_container:
        name: "geth_tmp"
        state: started
        image: "{{ eth1_image_name }}"
        pull: true
        restart_policy: no
        auto_remove: false
        detach: no
        network_mode: host
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
        volumes: "{{eth1_volumes}}"
        command: "{{ geth_init_args }}"
        env: "{{ eth1_env | default({}) }}"
        user: "{{ eth1_user_id }}"
