- name: Setup machine for deployment
  hosts: beacon
  gather_facts: true
  serial: 20
  tasks:
    - name: Add SSH keys from Github users
      loop: "{{ github_user_pubkeys }}"
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "https://github.com/{{ item }}.keys"
    - name: Setup swap
      become: true
      block:
        - name: Swap file creation
          vars:
            swap_file_size_mb: "4000m"
          include_role:
            name: geerlingguy.swap
    - name: Ubuntu universe repo and update
      become: true
      block:
        - name: Debug distribution
          debug:
            var: ansible_distribution_release
        # Necessary for Docker install to find dependencies in ubuntu 18
        - name: Add universe repository
          apt_repository:
            repo: "deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} universe"
            state: present
          when: (ansible_distribution_release == 'bionic') or (ansible_distribution_release == 'focal')
        - name: Run "apt-get update" to ensure available packages are up to date
          apt:
            update_cache: yes
    - name: Docker with dependencies and user role
      become: true
      block:
        - name: Docker
          include_role:
            name: geerlingguy.docker
        - name: Docker Python wrapper
          apt:
            name: python3-docker
            state: present
        - name: Add ansible user to docker group
          shell: 'usermod -aG docker {{ ansible_user }}'
