- name: Start eth1 node for explorer
  hosts: "eth1:&explorer"
  gather_facts: true
  serial: 20
  tasks:
    - name: Start eth1 node container
      docker_container:
        name: "{{ eth1_container_name }}"
        state: started
        image: "{{ eth1_image_name }}"
        pull: true
        restart_policy: unless-stopped
        memory_swappiness: 0
        kernel_memory: "{{eth1_kernel_memory}}"
        network_mode: bridge
        networks:
          - name: "{{explorer_docker_network_name}}"
            ipv4_address: "172.1.1.103"
        ports:
          - "{{eth1_rpc_port}}:{{eth1_rpc_port}}"
          - "{{eth1_ws_rpc_port}}:{{eth1_ws_rpc_port}}"
        restart: "{{ eth1_require_restart | default(false) }}"
        log_options: "{{ common_log_options }}"
        log_driver: "{{ common_log_driver }}"
        volumes: "{{eth1_volumes}}"
        memory: "{{eth1_memory}}"
        memory_swap: "{{eth1_memory}}"
        command: "{{ eth1_start_args }}"
        env: "{{ eth1_env | default({}) }}"
        user: "{{ eth1_user_id }}"
