- name: Start explorer
  hosts: explorer
  gather_facts: true
  serial: 20
  tasks:
    - name: Nginx proxy server
      docker_container:
        name: nginx-proxy
        state: started
        image: "jwilder/nginx-proxy:latest"
        restart_policy: unless-stopped
        network_mode: host
        restart: false
        volumes:
          - "/etc/nginx/certs:/etc/nginx/certs"
          - "/etc/nginx/vhost.d:/etc/nginx/vhost.d"
          - "/usr/share/nginx/html:/usr/share/nginx/html"
          - "/var/run/docker.sock:/tmp/docker.sock:ro"

    - name: Nginx proxy companion
      docker_container:
        name: nginx-proxy-companion
        state: started
        image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
        restart_policy: unless-stopped
        network_mode: host
        restart: false
        volumes:
          - "/etc/nginx/certs:/etc/nginx/certs"
          - "/etc/nginx/vhost.d:/etc/nginx/vhost.d"
          - "/usr/share/nginx/html:/usr/share/nginx/html"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        env:
          DEFAULT_EMAIL: "{{letsencrypt_email}}"
          NGINX_PROXY_CONTAINER: nginx-proxy

    - name: Start Eth2 explorer
      docker_container:
        name: "{{ explorer_container_name }}"
        state: started
        image: "{{ explorer_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: bridge
        networks:
          - name: "{{explorer_docker_network_name}}"
            ipv4_address: "172.1.1.101"
        ports: # Cannot run on host network due to nginx proxy
          - "5000:9333"
        restart: "{{ explorer_require_restart | default(false) }}"
        memory: "{{explorer_memory}}"
        command: "{{ explorer_start_args }}"
        volumes: "{{explorer_volumes}}"
        env:
          VIRTUAL_HOST: "{{ explorer_domain }}"
          VIRTUAL_PORT: "'5000'"
          LETSENCRYPT_HOST: "{{ explorer_domain }}"
          LETSENCRYPT_EMAIL: "{{ letsencrypt_email }}"
